### ISSUE TITLE
I want to join AIMU

### ISSUE THREAD

**Issue by AvinashProgrammer** [A-I-M-U/AIMU#2]
Hello AIMU Team,
I'm Avinash and want to join AIMU group. I would like to make a free canvas course but I'm not so professional. My sololearn profile is https://www.sololearn.com/Profile/20294037/?ref=app (Jethalal).

#jaiAIMU

**Comment by vinaykumargb** [comment]
Hello, @AvinashProgrammer!

It's great to have you in our team. Feel free to make your courses on Canvas, and publish it in our organization repository. Anyways, it doesn't matter weather you're a professional coder or not. Ofcourse, every great programmers once a beginner. Only thing that matters for us, is content that could be helpful to others: beginners or intermediate coders. Now, you'll be a member of our group, please be polite with other members, and happy coding. :)

Thank you.
